name: Daily COPR status

on:
  schedule:
    - cron: "30 7 * * 1-5"
  workflow_dispatch:

jobs:
  COPR_build_status:
    uses: pvermeer/rpm-tools/.github/workflows/copr-status.yml@main
    with:
      spec_file: ./chromebook-linux-audio.spec
      copr_owner: pvermeer
      copr_project: chromebook-linux-audio
      copr_package: chromebook-linux-audio
